name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend-frontend-ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [back-end, front-end]

    steps:
      - uses: actions/checkout@v3

      # Python setup
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Installing dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit flake8 pytest
          if [ -f ${{ matrix.project }}/requirements.txt ]; then pip install -r ${{ matrix.project }}/requirements.txt; fi

      # Run security scan
      - name: Run Bandit security scan
        run: |
          bandit -r ${{ matrix.project }}/ -ll

      # Linting
      - name: Run flake8 linting
        run: |
          flake8 ${{ matrix.project }}/

      # Run tests
      - name: Run tests
        run: |
          if [ -d ${{ matrix.project }}/tests ]; then pytest ${{ matrix.project }}/tests; fi
